name: Publish a new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  strategy:
    fail-fast: true

  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: |
          mkdir docs
          python -m nox -s generate-docs -- -o ./docs/release
          cp -r ./docs/release ./docs/latest

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Release docs: %{{  }} ({long-sha})"

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install git+https://github.com/hikari-py/hikari.git .[nox]

    - name: publish
      run: |
        python -m nox -s publish -- -u __token__ -p ${{ secrets.PYPI_TOKEN }} -t ${{ secrets.PYPI_TARGET }}

  tag-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create tag
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
